//Auto-generated by RSP Compiler
//Source: listView.rsp.html
part of prova;

/** Template, listView, for rendering the view. */
Future listView(HttpConnect connect, {List<User> users}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  Rsp.init(connect, "text/html; charset=utf-8");

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>

    <table border="1px" cellspacing="0">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Username</th>
      </tr>
"""); //#2

  for (var user in users) { //for#15

    response.write("""      <tr>
        <td>"""); //#16

    response.write(Rsp.nnx(user.fName)); //#17


    response.write("""</td>
        <td>"""); //#17

    response.write(Rsp.nnx(user.lName)); //#18


    response.write("""</td>
        <td>"""); //#18

    response.write(Rsp.nnx(user.username)); //#19


    response.write("""</td>
      </tr>
"""); //#19
  } //for

  response.write("""    </table>
  </body>
</html>
"""); //#22

  return Rsp.nnf();
}
